### ISSUE TITLE
Easing Accessibility

### ISSUE THREAD

**Issue by sherlockwisdom** [SMSwithoutBorders/SMSwithoutBorders_Admin#10]
**Observation:**
Currently it when sending a new message it is expected to select the sending modem, but knowing which modem to use can be very difficult as factors like isp etc need to be considered in the choice. All this information is present in the list of modems being shown.

**Proposal:**
A button under each modem which can automatically populate the modem in the New Message tag modem space

**Comment by sherlockwisdom** [comment]
Currently does not match what was proposed for the issue, current commit adds a good feature to it - but I think we can keep this issue open pending the proposed action

**Comment by nSedrickm** [comment]
Please better explain what you mean/expect.

Each modem has the option to be set as the default sending device which in turn gets auto-populated on the SMS page.

The user can also view details for each modem so they can make an informed decision.

I do not understand what is lacking here

**Comment by sherlockwisdom** [comment]
If we look at the standard way modem managers work (which this is supposed to function as), we have a simple intuitive logical flow:
select modem -> get access to it's functionalities
This is a typical Object oriented thinking problem, which was already solved right by having the user be able to see the SMS logs per modem already, would be intuitive and serve it's purpose as a local modem manager if SMS can be sent from each modem with the same standards it takes to see incoming messages
